import type { EditorComponentRegistryItem } from "./types";

export const EDITOR_COMPONENT_REGISTRY: EditorComponentRegistryItem[] = [
  {
    componentId: "executive.dashboard-shell",
    sourceLibrary: "executive",
    category: "dashboard",
    displayName: "Universal executive dashboard shell",
    adapter: "ExecutiveDashboardWidgetAdapter",
    propsSchema: { source: "ExecutiveDashboardSource" },
    dataRequirements: ["CSV records", "dataset profile", "dashboard plan"],
    minSize: { w: 960, h: 560 },
    defaultSize: { w: 1216, h: 640 },
    supportedIntents: ["generic_operations", "financial_plan_fact", "workload", "population", "any_csv"],
    aiDescription: "Use for any user CSV when the dashboard should keep the AZS dark executive styling but map arbitrary columns into KPI hierarchy, filters, trends, rankings, alerts and breakdowns.",
    sourceUrl: "internal://executive-dashboard-shell",
  },
  {
    componentId: "azs.dashboard-shell",
    sourceLibrary: "azs",
    category: "dashboard",
    displayName: "AZS Moscow dashboard shell",
    adapter: "AzsDashboardWidgetAdapter",
    propsSchema: { data: "AzsDataset | undefined", initialView: "dashboard | fuel | prices | reports" },
    dataRequirements: ["registry summary", "queue summary", "hourly fuel and queue time series", "prices by net"],
    minSize: { w: 960, h: 560 },
    defaultSize: { w: 1216, h: 640 },
    supportedIntents: ["fuel_dashboard", "executive_summary", "filters", "azs", "moscow_fuel_monitoring"],
    aiDescription: "Use for the full Moscow AZS operational dashboard: tabs, company filters, KPI hierarchy, fuel availability, queue trend, restrictions, network donut breakdown, fuel supply, prices and report summary.",
    sourceUrl: "/public/azs-data",
  },
  {
    componentId: "tremor.metric-card",
    sourceLibrary: "tremor",
    category: "kpi",
    displayName: "Tremor KPI metric card",
    adapter: "TremorMetricCardAdapter",
    propsSchema: { value: "number", delta: "string", progress: "number", tone: "green | red | orange | blue" },
    dataRequirements: ["single numeric measure"],
    minSize: { w: 180, h: 132 },
    defaultSize: { w: 252, h: 152 },
    supportedIntents: ["kpi", "status", "plan_fact", "risk"],
    aiDescription: "Use for one executive value, status KPI, plan/fact metric or compact operational counter.",
    sourceUrl: "https://github.com/tremorlabs/tremor",
  },
  {
    componentId: "tremor.line-chart",
    sourceLibrary: "tremor",
    category: "chart",
    displayName: "Tremor line chart",
    adapter: "TremorLineChartAdapter",
    propsSchema: { data: "array", index: "string", categories: "string[]" },
    dataRequirements: ["time column", "one or more numeric series"],
    minSize: { w: 420, h: 220 },
    defaultSize: { w: 620, h: 260 },
    supportedIntents: ["trend", "forecast", "time_comparison"],
    aiDescription: "Use for dynamics over time, forecast, availability trends and plan/fact over dates.",
    sourceUrl: "https://tremor.so",
  },
  {
    componentId: "tremor.bar-chart",
    sourceLibrary: "tremor",
    category: "chart",
    displayName: "Tremor bar chart",
    adapter: "TremorBarChartAdapter",
    propsSchema: { data: "array", index: "string", categories: "string[]" },
    dataRequirements: ["category column", "numeric value"],
    minSize: { w: 360, h: 220 },
    defaultSize: { w: 460, h: 260 },
    supportedIntents: ["ranking", "comparison", "queues"],
    aiDescription: "Use for rankings, queues, top-N, district or company comparisons.",
    sourceUrl: "https://github.com/tremorlabs/tremor",
  },
  {
    componentId: "tremor.donut-chart",
    sourceLibrary: "tremor",
    category: "chart",
    displayName: "Tremor donut chart",
    adapter: "TremorDonutChartAdapter",
    propsSchema: { data: "array", category: "string", index: "string" },
    dataRequirements: ["small composition, 2-5 categories"],
    minSize: { w: 260, h: 220 },
    defaultSize: { w: 330, h: 260 },
    supportedIntents: ["composition", "status_mix"],
    aiDescription: "Use only for a compact 2-5 part status mix where total is meaningful.",
    sourceUrl: "https://tremor.so",
  },
  {
    componentId: "tremor.table",
    sourceLibrary: "tremor",
    category: "table",
    displayName: "Tremor exception table",
    adapter: "TremorTableAdapter",
    propsSchema: { rows: "array", columns: "string[]" },
    dataRequirements: ["detail rows"],
    minSize: { w: 420, h: 220 },
    defaultSize: { w: 520, h: 260 },
    supportedIntents: ["exceptions", "details", "audit", "action_list"],
    aiDescription: "Use for problematic objects, drill-through details, audit rows and action lists.",
    sourceUrl: "https://github.com/tremorlabs/tremor",
  },
  {
    componentId: "tremor.area-chart",
    sourceLibrary: "tremor",
    category: "chart",
    displayName: "Tremor AreaChart",
    adapter: "TremorAreaChartAdapter",
    propsSchema: { data: "array", index: "string", categories: "string[]" },
    dataRequirements: ["time column", "one or more numeric series"],
    minSize: { w: 420, h: 220 },
    defaultSize: { w: 520, h: 260 },
    supportedIntents: ["trend", "volume", "stacked_time_series"],
    aiDescription: "Official Tremor AreaChart for filled time-series dynamics.",
    sourceUrl: "https://github.com/tremorlabs/tremor",
  },
  {
    componentId: "tremor.funnel-chart",
    sourceLibrary: "tremor",
    category: "chart",
    displayName: "Tremor FunnelChart",
    adapter: "TremorFunnelChartAdapter",
    propsSchema: { data: "array", category: "string", index: "string" },
    dataRequirements: ["ordered stages", "numeric value"],
    minSize: { w: 360, h: 220 },
    defaultSize: { w: 460, h: 260 },
    supportedIntents: ["funnel", "conversion", "pipeline"],
    aiDescription: "Official Tremor FunnelChart for conversion and staged pipelines.",
    sourceUrl: "https://github.com/tremorlabs/tremor",
  },
  {
    componentId: "tremor.scatter-chart",
    sourceLibrary: "tremor",
    category: "chart",
    displayName: "Tremor ScatterChart",
    adapter: "TremorScatterChartAdapter",
    propsSchema: { data: "array", x: "string", y: "string", category: "string" },
    dataRequirements: ["x numeric", "y numeric", "category label"],
    minSize: { w: 420, h: 220 },
    defaultSize: { w: 520, h: 260 },
    supportedIntents: ["correlation", "quadrant", "risk_vs_load"],
    aiDescription: "Official Tremor ScatterChart for correlation analysis.",
    sourceUrl: "https://github.com/tremorlabs/tremor",
  },
  ...["spark-area-chart", "spark-line-chart", "spark-bar-chart"].map((name) => ({
    componentId: `tremor.${name}`,
    sourceLibrary: "tremor" as const,
    category: "chart" as const,
    displayName: `Tremor ${name.replace(/(^|-)([a-z])/g, (_, __, letter: string) => letter.toUpperCase())}`,
    adapter: `Tremor${name}Adapter`,
    propsSchema: { data: "array", index: "string", categories: "string[]" },
    dataRequirements: ["compact time series"],
    minSize: { w: 220, h: 120 },
    defaultSize: { w: 320, h: 180 },
    supportedIntents: ["sparkline", "compact_kpi_trend"],
    aiDescription: `Official Tremor ${name} for compact trend cards.`,
    sourceUrl: "https://github.com/tremorlabs/tremor",
  })),
  ...["bar-list", "category-bar", "delta-bar", "marker-bar", "progress", "tracker"].map((name) => ({
    componentId: `tremor.${name}`,
    sourceLibrary: "tremor" as const,
    category: "chart" as const,
    displayName: `Tremor ${name.replace(/(^|-)([a-z])/g, (_, __, letter: string) => letter.toUpperCase())}`,
    adapter: `Tremor${name}Adapter`,
    propsSchema: { value: "number", data: "array" },
    dataRequirements: ["numeric value or status array"],
    minSize: { w: 240, h: 120 },
    defaultSize: { w: 340, h: 180 },
    supportedIntents: ["ranking", "status", "progress", "threshold"],
    aiDescription: `Official Tremor ${name} visualization primitive.`,
    sourceUrl: "https://github.com/tremorlabs/tremor",
  })),
];

export function getEditorComponentRegistry() {
  return EDITOR_COMPONENT_REGISTRY;
}

export function getCompactEditorComponentRegistry() {
  return EDITOR_COMPONENT_REGISTRY.map((item) => ({
    componentId: item.componentId,
    sourceLibrary: item.sourceLibrary,
    category: item.category,
    displayName: item.displayName,
    dataRequirements: item.dataRequirements,
    defaultSize: item.defaultSize,
    supportedIntents: item.supportedIntents,
    aiDescription: item.aiDescription,
  }));
}

export function getRegistryItem(componentId: string) {
  return EDITOR_COMPONENT_REGISTRY.find((item) => item.componentId === componentId);
}
